pub mod build;
pub mod builder;
pub mod codegen;
pub mod constraints;
pub mod display;
pub mod indenting;
pub mod infer;
pub mod instructions;
pub mod prelude;
pub mod program;
pub mod registers;
pub mod solver;
pub mod types;
pub mod variables;

pub use build::{BuildError, CBuild, Compiled, RunReport, Source};
pub use builder::{FunctionBuilder, InstructionBuilder};
pub use codegen::{CodegenError, CompilerError};
pub use constraints::Constraint;
pub use infer::{Constraints, Inference, Solved};
pub use instructions::Instr;
pub use prelude::PreludeFn;
pub use program::{Function, Program, type_var_generator_for_function};
pub use registers::{Reg, RegGenerator, RegId, RegisterFile};
pub use solver::{Solver, TypeError};
pub use types::{Existential, FuncType, Row, Type};
pub use variables::{TypeVar, TypeVarGenerator};
